version: "3.8"
services:
  ai-reviewer:
    build: .
    image: ai-reviewer:latest
    container_name: ai-reviewer
    restart: always
    ports:
      - "8080:8080"
    environment:
      # GitLab
      - GITLAB_BASE_URL=
      - GITLAB_API_TOKEN=
      # Jira
      - JIRA_BASE_URL=
      - JIRA_USERNAME=
      - JIRA_API_TOKEN=
      # SMTP (optional)
      - SMTP_HOST=
      - SMTP_PORT=25
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SMTP_AUTH=false
      - SMTP_STARTTLS=false
      - NOTIFY_ADMIN_EMAIL=
      - NOTIFY_FROM_EMAIL=
      # Logs
      - LOG_DIR=/var/log/ai-reviewer
    volumes:
      - ai-reviewer-logs:/var/log/ai-reviewer
volumes:
  ai-reviewer-logs:
